### PR TITLE
ENH: flush after each event and on stop

### PR DESCRIPTION
**Pull request by tacaswell**
This makes sure that other programs (like pymca) will see updates as
the come in.

### CODE REVIEW

**Comment by danielballan** [comment]
@gwbischof Note that in order to test this at CHX you will need to add `flush=True` to their `Serializer` instantiation.

**Comment by tacaswell** [comment]
Thanks for the commits @danielballan !

**Comment by danielballan** [comment]
Rebased to pick up #9 for compatibility with the new suitcase-utils.

**Comment by danielballan** [comment]
I added a test to verify that this closes #7. Without the fix in 838887d, the test raises:

```
suitcase.utils.SuitcaseUtilsValueError: The postfix 'my_file.spec' has already been used.
```

as we have seen in the wild. With the fix, it passes.

**Comment by jklynch** [comment]
Good use of tell(). Not a method I see very often.

**Pull request merged**
